# Generated by Django 5.1.4 on 2025-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comm', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
